// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSKns3EWfIjiKCb7Y8spjvogrHXht_cjo',
    appId: '1:300911203398:web:2d2e6b74ccff819b10a647',
    messagingSenderId: '300911203398',
    projectId: 'sneaker-app-2cbcc',
    authDomain: 'sneaker-app-2cbcc.firebaseapp.com',
    storageBucket: 'sneaker-app-2cbcc.appspot.com',
    measurementId: 'G-XLJSRV2SZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGIlgXQryCaKtMZ7wVnnitE1LA0Xaf8eU',
    appId: '1:300911203398:android:0491dc0e632fd8d110a647',
    messagingSenderId: '300911203398',
    projectId: 'sneaker-app-2cbcc',
    storageBucket: 'sneaker-app-2cbcc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhdT2aIkYL3f21FdHNsvvpoKsee0NI4Zs',
    appId: '1:300911203398:ios:4a6e2b7a632ef96a10a647',
    messagingSenderId: '300911203398',
    projectId: 'sneaker-app-2cbcc',
    storageBucket: 'sneaker-app-2cbcc.appspot.com',
    iosBundleId: 'com.example.nike',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhdT2aIkYL3f21FdHNsvvpoKsee0NI4Zs',
    appId: '1:300911203398:ios:a4a11eaa8746e51710a647',
    messagingSenderId: '300911203398',
    projectId: 'sneaker-app-2cbcc',
    storageBucket: 'sneaker-app-2cbcc.appspot.com',
    iosBundleId: 'com.example.nike.RunnerTests',
  );
}
